FROM node:16

RUN mkdir dist
WORKDIR /dist

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# RUN npm install -g pm2

EXPOSE ${WEBSOCKET_PORT}

ENV NODE_ENV=production
ENV WEBSOCKET_PORT=${WEBSOCKET_PORT}
ENV CORS_ORIGIN_DOMAIN=${CORS_ORIGIN_DOMAIN}
ENV SENTRY_DSN=${SENTRY_DSN}
ENV BOT_TOKEN=${BOT_TOKEN}
ENV WEBSOCKET_ADMIN_USERNAME=${WEBSOCKET_ADMIN_USERNAME}
ENV WEBSOCKET_ADMIN_PASSWORD=${WEBSOCKET_ADMIN_PASSWORD}
ENV SHOW_ENDPOINT=${SHOW_ENDPOINT}

CMD [ "node", "./build/src/index.js" ]